// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/*
 * main class
 */
package ingdelsw.fallsimulator;

import ingdelsw.fallsimulator.controller.EventHandler;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class FallSimulator extends Application{

	//javaFX entry point
    @Override
    public void start(Stage primaryStage) {
    	
    	//get singleton instances
        EventHandler eventHandler = EventHandler.getHandler();
        
        //full screen on application opening 
        primaryStage.setMaximized(true);
    
        //scene configuration
        Scene scene = new Scene(eventHandler.getLayout().getBorderPane(), 1000, 700);
        primaryStage.setTitle("Fall Simulator");
        primaryStage.setScene(scene);
        primaryStage.show(); 
    }
    
    public static void main(String[] args) {
        launch(args);
    }
}
