// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/*
 * main class
 */
package ingdelsw.fallsimulator;

import ingdelsw.fallsimulator.controller.EventHandler;
import javafx.application.Application;
import javafx.geometry.Rectangle2D;
import javafx.scene.Scene;
import javafx.stage.Screen;
import javafx.stage.Stage;

public class FallSimulator extends Application{

	//javaFX entry point
    @Override
    public void start(Stage primaryStage) {
    	
    	//get eventHandler singleton instance
        EventHandler eventHandler = EventHandler.getHandler();
        
        // get screen size
        Rectangle2D visualBounds = Screen.getPrimary().getVisualBounds();
    
        //scene configuration: Scene(root node, width, height)
        Scene scene = new Scene(eventHandler.getLayout().getBorderPane(), visualBounds.getWidth(), visualBounds.getHeight());
        
        //full screen when application is first opened
        primaryStage.setMaximized(true);
        
        primaryStage.setTitle("Fall Simulator"); //set title
        primaryStage.setScene(scene); //set the scene on the stage
        primaryStage.show(); //show stage
    }
    
    public static void main(String[] args) {
        launch(args);
    }
}
