// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator;

import ingdelsw.FallSimulator.Math.Point;

/************************************************************/
/**
 * 
 */
public class InputManager {
	/**
	 * 
	 */
	private Point startPoint;
	/**
	 * 
	 */
	private Point endPoint;

	/**
	 * 
	 * @return 
	 */
	public Point getStartPoint() {
	}

	/**
	 * 
	 * @return 
	 */
	public Point getEndPoint() {
	}

	/**
	 * 
	 * @param startPoint 
	 */
	public void setStartPoint(Point startPoint) {
	}

	/**
	 * 
	 * @param endPoint 
	 */
	public void setEndPoint(Point endPoint) {
	}
}
