// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator;

import ingdelsw.FallSimulator.Math.Point;

/************************************************************/
/**
 * 
 */
public class Mass {
	/**
	 * 
	 */
	private MassIcon iconType;
	/**
	 * 
	 */
	private Point position;
}
