// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

import ingdelsw.FallSimulator.Math.Point;

class Circumference extends Curve {
	
	private double r;
	private int convexity;

	public Circumference(Point startPoint, Point endPoint, double r, int convexity) {
    	super(startPoint, endPoint);
        this.r=r;
        this.convexity=convexity;
    }
	
	public void setR(double r) {
		this.r=r;
	}

	
	public double getR() {
		return r;
	}

	
	public double evaluateFunction(double var) {
    	return Math.sqrt(2*var*r - Math.pow(var, 2));
    }

	
	public float aCoefficient() {
	}

	
	public float bCoefficient() {
	}

	
	public float cCoefficient() {
	}

	
	public float delta() {
	}

	
	public float xCenter(Point startPoint) {
	}

	
	public float yCenter(Point startPoint) {
	}
}
