// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

import ingdelsw.FallSimulator.Math.Point;

/************************************************************/
/**
 * 
 */
class Circumference extends Curve {
	/**
	 * 
	 */
	private float r;
	/**
	 * 
	 */
	private int convexity;

	/**
	 * 
	 * @param r 
	 */
	public void setR(float r) {
	}

	/**
	 * 
	 * @return 
	 */
	public float getR() {
	}

	/**
	 * 
	 * @param var 
	 * @return 
	 */
	public float evaluateFunction(float var) {
	}

	/**
	 * 
	 * @return 
	 */
	public float aCoefficient() {
	}

	/**
	 * 
	 * @return 
	 */
	public float bCoefficient() {
	}

	/**
	 * 
	 * @return 
	 */
	public float cCoefficient() {
	}

	/**
	 * 
	 * @return 
	 */
	public float delta() {
	}

	/**
	 * 
	 * @param startPoint 
	 * @return 
	 */
	public float xCenter(Point startPoint) {
	}

	/**
	 * 
	 * @return 
	 * @param startPoint 
	 */
	public float yCenter(Point startPoint) {
	}
}
