// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

import ingdelsw.FallSimulator.Math.Point;

/************************************************************/
/**
 * 
 */
public class CubicSpline extends Curve
 {
				/**
				 * 
				 */
				public CubicSegment[] ;
				/**
				 * 
				 */
				public Point[] controlPoints;
}
