// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

import java.util.ArrayList;

import ingdelsw.FallSimulator.Math.Point;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.paint.Color;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public abstract class Curve {
	
	protected static final Logger LOGGER = LogManager.getLogger();
	
	protected double intervalX,intervalY;
	protected Point startPoint, endPoint;
	
	public abstract ArrayList<Point> calculatePointList();
	public abstract double[] calculateSlopes();

	public Curve(Point startPoint, Point endPoint)
	{
		this.startPoint = startPoint;
		this.endPoint = endPoint;
		intervalX = endPoint.getX()-startPoint.getX();
		intervalY = endPoint.getY()-startPoint.getY();
	}
	
	
	public void drawCurve(GraphicsContext gc) {
        gc.setStroke(Color.BLUE);
        gc.setLineWidth(2);
        ArrayList<Point> points = calculatePointList();
        for (int i = 0; i < points.size() - 1; i++) 
        	gc.strokeLine(points.get(i).getX(), points.get(i).getY(), points.get(i+1).getX(), points.get(i+1).getY());
    }
}
