// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

import java.util.ArrayList;

import ingdelsw.FallSimulator.Math.Point;

public abstract class Curve {
	
	protected double intervalX,intervalY;

	public Curve(Point startPoint, Point endPoint)
	{
		intervalX = endPoint.getX()-startPoint.getX();
		intervalY = endPoint.getY()-startPoint.getY();
	}
	
	public abstract ArrayList<Point> calculatePointList(Point startPoint, int numPoints);
	
	public void drawCurve(Point startPoint, int numPoints) {
	}
}
