// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.fallsimulator.math.curves;

import java.util.Random;

import ingdelsw.fallsimulator.math.Point;

public abstract class Curve {
	
	protected double intervalX;
	protected double intervalY;
	protected Point startPoint;
	protected Point endPoint;
	protected int red;
	protected int green;
	protected int blue;
	protected static final int  NUMPOINTS = 7000;
	
	public abstract Point[] calculatePoints();
	public abstract double[] calculateSlopes();
	public abstract String curveName();
	
	protected Curve(Point startPoint, Point endPoint)
	{
		this.startPoint = startPoint;
		this.endPoint = endPoint;
		intervalX = endPoint.getX()-startPoint.getX();
		intervalY = endPoint.getY()-startPoint.getY();
		
	}
	
	Random random = new Random();
	public void setRandomColors()
	{
		red = random.nextInt(230);
		blue = random.nextInt(230);
		green = random.nextInt(230);
	}
	
	public void setRed(int red)
	{
		this.red = red;
	}
	
	public void setGreen(int green)
	{
		this.green = green;
	}
	
	public void setBlue(int blue)
	{
		this.blue = blue;
	}
	
	public int getRed()
	{
		return red;
	}
	
	public int getGreen()
	{
		return green;
	}
	
	public int getBlue()
	{
		return blue;
	}
	
	public static int getNumPoints()
	{
		return NUMPOINTS;
	}
	
	public Point getStartPoint()
	{
		return startPoint;
	}
	
	public Point getEndPoint()
	{
		return endPoint;
	}
	
}
