// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;


public class Cycloid extends Curve {
	
	private double r;
	
	private float alfa;

	public float evaluateX(float a) {
	}

	
	public float evaluateY(float a) {
	}

	
	public float calculateR(float x, float y) {
	}

	
	public float calculateAlfa(float x, float y) {
	}
}
