// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

/************************************************************/
/**
 * 
 */
public class Parabola extends Curve {
	/**
	 * 
	 */
	public float a;

	/**
	 * 
	 * @return 
	 */
	public float getA() {
	}

	/**
	 * 
	 * @return 
	 * @param x 
	 */
	public float evaluateY(float x) {
	}
}
