// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

import ingdelsw.FallSimulator.Math.Point;

public class Parabola extends Curve {
	
	public double a;
	
	public Parabola(Point startPoint, Point endPoint) {
    	super(startPoint,endPoint);
        a=(endPoint.getX()-startPoint.getX())/Math.pow(endPoint.getY()-startPoint.getY(), 2);
    }

	public double getA() {
		return a;
	}

	public double evaluateX(double y) {
		return a*Math.pow(y, 2);
    }
	
	public Point[] calculatePoints() 
    {
    	Point[] points = new Point[numPoints];
    	double x = startPoint.getX();
    	double y = startPoint.getY();
    	double t, yPow;
    	for (int i=0; i < numPoints; i++) {
    		t = (double) i / (numPoints - 1); 
            yPow = intervalY * Math.pow(t, 3);  
            y = startPoint.getY() + yPow;
            x = startPoint.getX() + evaluateX(y-startPoint.getY());
            points[i] = new Point(x,y);
    		LOGGER.debug("punto " + i +"-esimo - X : " + x + " Y : "+ y);
        }
    	return points;
	}
	
	public String curveName()
	{
		return "Parabola";
	}
}
