// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

import ingdelsw.FallSimulator.Math.Point;

public class Parabola extends Curve {
	
	public double a;
	
	public Parabola(Point startPoint, Point endPoint) {
    	super(startPoint,endPoint);
        a=(endPoint.getX()-startPoint.getX())/Math.pow(endPoint.getY()-startPoint.getY(), 2);
    }

	public double getA() {
		return a;
	}

	public double evaluateY(double x) {
    	return Math.sqrt(x/a);
    }
}
