// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FallSimulator;

/************************************************************/
/**
 * 
 */
public class CubicSpline extends Curve
 {
				/**
				 * 
				 */
				public CubicSegment[] ;
				/**
				 * 
				 */
				public Point[] controlPoints;
}
