// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FallSimulator;

/************************************************************/
/**
 * 
 */
public abstract class Curve {
	/**
	 * 
	 */
	protected float intervalX;
	/**
	 * 
	 */
	protected float intervalY;

	/**
	 * 
	 * @return 
	 * @param startPoint 
	 * @param numPoints 
	 */
	public abstract Point calculatePointList(Point startPoint, int numPoints);

	/**
	 * 
	 * @param startPoint 
	 * @param numPoints 
	 */
	public void drawCurve(Point startPoint, int numPoints) {
	}
}
