// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FallSimulator;

/************************************************************/
/**
 * 
 */
public class Interface {
				/**
				 * 
				 */
				public InputManager ;
				/**
				 * 
				 */
				public SimulationManager ;
				/**
				 * 
				 */
				private UIStates states;
}
