// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FallSimulator;

/************************************************************/
/**
 * 
 */
public class Mass {
	/**
	 * 
	 */
	private MassIcon iconType;
	/**
	 * 
	 */
	private Point position;
}
