// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FallSimulator;

/************************************************************/
/**
 * 
 */
public enum MassIcon {
	/**
	 * 
	 */
	GALILEO,
	/**
	 * 
	 */
	NEWTON,
	/**
	 * 
	 */
	LEIBNITZ,
	/**
	 * 
	 */
	BERNOULLI,
	/**
	 * 
	 */
	JAKOB;
}
