// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FallSimulator;

/************************************************************/
/**
 * 
 */
public class Point {
	/**
	 * 
	 */
	private Real x;
	/**
	 * 
	 */
	private Real y;

	/**
	 * 
	 * @return 
	 */
	public Real getX() {
	}

	/**
	 * 
	 * @return 
	 */
	public Real getY() {
	}
}
