// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FallSimulator;

/************************************************************/
/**
 * 
 */
public class SimulationManager {
				/**
				 * 
				 */
				public Mass ;
				/**
				 * 
				 */
				public Curve ;
}
