// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FallSimulator;

/************************************************************/
/**
 * 
 */
public enum UIStates {
	/**
	 * 
	 */
	WAITING_FOR_START_POINT,
	/**
	 * 
	 */
	WAITING_FOR_END_POINT,
	/**
	 * 
	 */
	CHOOSING_CURVE,
	/**
	 * 
	 */
	INSERTING_INTERMEDIATE_POINTS,
	/**
	 * 
	 */
	CHOOSING_CONVEXITY,
	/**
	 * 
	 */
	CHOOSING_RADIUS,
	/**
	 * 
	 */
	CHOOSING_MASS,
	/**
	 * 
	 */
	WAITING_TO_START_SIMULATION,
	/**
	 * 
	 */
	SIMULATING,
	/**
	 * 
	 */
	SHOWING_SIMULATION_RESULTS;
}
