// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.fallsimulator.simulation;


 
public enum MassIcon {
	/**
	 * 
	 */
	GALILEO,
	/**
	 * 
	 */
	NEWTON,
	/**
	 * 
	 */
	LEIBNITZ,
	/**
	 * 
	 */
	BERNOULLI,
	/**
	 * 
	 */
	JAKOB;
}
