// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

import ingdelsw.FallSimulator.Math.Point;

/************************************************************/
/**
 * 
 */
public class CubicSegment {
	/**
	 * 
	 */
	private float a;
	/**
	 * 
	 */
	public float b;
	/**
	 * 
	 */
	public float c;
	/**
	 * 
	 */
	public float d;
	/**
	 * 
	 */
	public Point point0;
	/**
	 * 
	 */
	public Point point1;
	/**
	 * 
	 */
	protected float dSeconda0;
	/**
	 * 
	 */
	public float dPrima1;
	/**
	 * 
	 */
	public float Property9;
	/**
	 * 
	 */
	public float dSeconda1;
}
