// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ingdelsw.FallSimulator.Math.Curves;

/************************************************************/
/**
 * 
 */
public class Cycloid extends Curve {
	/**
	 * 
	 */
	private float r;
	/**
	 * 
	 */
	private float alfa;

	/**
	 * 
	 * @param a 
	 * @return 
	 */
	public float evaluateX(float a) {
	}

	/**
	 * 
	 * @param a 
	 * @return 
	 */
	public float evaluateY(float a) {
	}

	/**
	 * 
	 * @return 
	 * @param x 
	 * @param y 
	 */
	public float calculateR(float x, float y) {
	}

	/**
	 * 
	 * @return 
	 * @param x 
	 * @param y 
	 */
	public float calculateAlfa(float x, float y) {
	}
}
